name: Build and Deploy to Kubernetes on GCP

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1.1.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials staging --zone asia-southeast2 --project project-stg

    - name: Get the current commit version
      run: echo "::set-env name=VERSION::$(git rev-parse --short HEAD)"

    - name: Build the Docker image
      run: |
        docker build -t node-express-rest:${{ env.VERSION }} .

    - name: Authenticate with the container registry
      run: |
        echo "${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

    - name: Tag and push the Docker image
      run: |
        docker tag node-express-rest:${{ env.VERSION }} gcr.io/project-stg/node-express-rest:${{ env.VERSION }}
        docker push gcr.io/project-stg/node-express-rest:${{ env.VERSION }}

    - name: Deploy to Kubernetes
      run: |
        sed -i "s/<image_name>/gcr.io/project-stg/node-express-rest:${{ env.VERSION }}/g" k8s-manifest/Deployment.yml
        kubectl apply -f k8s-manifests/
